sonar.projectKey=DiFedeCorp_DemoTour_c29067b8-9a95-4cd8-b99f-aa3dff077929
sonar.sources=src/main/java
sonar.tests=src/test/java

# Binaries compilés par Maven
sonar.java.binaries=target/classes

# Rapport de couverture JaCoCo généré par Maven (phase verify)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
